version: '3'
services:
  telebot:
    build: .
    environment:
      #APITOKEN: 'YOUR_TELEGRAM_API_TOKEN'
      DRIVER_HOST: driver
      DRIVER_PORT: 4444
      DRIVER_API_PREFIX: /wd/hub
    restart: on-failure
  driver:
    image: selenium/standalone-chrome
    environment:
      START_XVFB: 'false'
    restart: on-failure
    volumes:
      - /dev/shm:/dev/shm
    